#version 460

#define TYPE int
#define TID  11

layout(local_size_x=1, local_size_y=1, local_size_z=1) in;

shared TYPE s_value;

layout(std430, binding=0) readonly buffer in_value_buffer
{
	TYPE in_value;
};

layout(std430, binding=1) writeonly buffer out_value_buffer
{
	TYPE[] out_value;
};

void main()
{
	if (gl_LocalInvocationID.x == TID)
	{
		//s_value = 47;
		s_value = in_value;
	}
	groupMemoryBarrier();

	out_value[gl_LocalInvocationID.x] = s_value;
}

